on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

name: Project check
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          if [ -f 'package.json' ]; then npm install; else echo 'Skip. The file package.json does not exist'; fi

      - name: Run checks
        run: |
          if [ -f 'package.json' ]; then npm run lint; else echo 'Skip. The file package.json does not exist'; fi

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          if [ -f 'package.json' ]; then npm install; else echo 'Skip. The file package.json does not exist'; fi

      - name: Run checks
        run: |
          if [ -f 'package.json' ]; then npm run check:format; else echo 'Skip. The file package.json does not exist'; fi
