name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  # специальное событие, которое происходит при ручном вызове workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: Build
        run: npm run build
        # env:
          # REACT_APP_BACKEND_URL: ${{ secrets.API_URL }}
      # - run: mkdir -p build
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: six-cities-back/

  deploy:
    needs: build
    runs-on: ununtu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      # загружаем ранее сохраненные артефакты
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: six-cities-back/
      - name: Copy build to the server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          rm: true
          source: build/*
          target: '~/six-cities/public'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
